---

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname

- name: "My Role"
  connection: local
  command: hostname
