sudo: required

notifications:
  email: false

language: python

python:
- "2.7"

install:
- pip install -r dev_requirements.txt

script:
- PYTHONPATH=. ${TRAVIS_BUILD_DIR}/test.sh

services:
  - docker
