---

- hosts: all
  gather_facts: false
  tasks:

  - name: simulate long running op (3 sec), wait for up to 5 sec, poll every 1 sec
    command: /bin/sleep 2
    async: 4
    register: derp

  - debug: msg={{derp}}

  - async_status: jid={{derp.ansible_job_id}}
    register: derp2

  - debug: msg={{derp2}}
